- .github/workflows/test.yml
- .gitignore
- index.js
- package.json
- test/index.test.js
- test/mocks/@actions/exec.js
This PR updates the action to only `git add` and `git diff-index` github/licensed's configured cache paths.
The `licensed env` command is available in the 2.5.0 release, which provides the data needed.  If the command isn't available then the action will default to the legacy behavior and add + check all files in the repo.
As part of this change I've also added stdout and stderr as supported arguments to the `@actions/exec` mock which will `@actions/exec.exec('echo')` with the provided options so as to preserve any options that capture output from the mocked process.
> Use licensed env to add data only under licensed `cache_paths`

- lib/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
Hit an error when trying to fetch/rebase using the `branch` workflow on a private repository
```
fatal: could not read Username for 'https://github.com': No such device or address
```
This was handled on pushing changes to GitHub by using authentication via the token provided by the `github_token` action input.  Using the same method here, which requires adding the remote earlier in the process.
> branch workflow operations need to use GitHub token auth

- .github/workflows/test.yml
- lib/index.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/index.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
This fixes an issue with the workflows where they were not failing appropriately based on `licensed status` calls on the target branch.
> Fail action if licensed status doesn't succeed on target branch

- lib/workflows/branch.js
- lib/workflows/push.js
- package-lock.json
- package.json
- test/workflows/branch.test.js
- test/workflows/push.test.js
a little cleanup to get onto core-managed output methods, and avoid stubbing console.log for tests.  stubbing `process.stdout.write` as part of `actions-mocks` might be nice as well, will look into that later
> Actions core 1.2.0

- README.md
- action.yml
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- package-lock.json
- package.json
- test/fixtures/testSearchResult.json
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
This PR adds in the option to cleanup branch workflow artifacts if they exist when `licensed status` succeeds on the users branch.  The extra action is gated by a new `cleanup_on_success` input flag.
1. close any open PR for the licenses branch, in the event that licenses were updated on the user branch directly
2. delete the created licenses branch if it exists
Tested this with a fake release branch on this repo, which showed that my original strategy to use `git show-ref` wouldn't work because the separate git origin used in this action, `licensed-ci-origin` hasn't been fetched when this code is run.  Updated to use `git ls-remote` and all is working 👍 
```
License checks succeeded. Cleaning up any open branches and PRs
git ls-remote --exit-code licensed-ci-origin …
```
> Cleanup branch workflow artifacts on success

- lib/utils.js
- lib/workflows/branch.js
- test/utils.test.js
- test/workflows/branch.test.js
This PR changes the method of updating the licenses branch in the `branch` workflow from rebasing to merging.
Rebasing could require use of `--force` or other workarounds when getting the licenses branch updated from the user's work branch.
Users might have rules in place on a repo that prohibit force pushes.  merging up is safer and easier to reason about, and gives users the option on how to merge the changes into the work branch - merge, squash, rebase
> Merge user branch into licenses branch in branch strategy workflow

- action.yml
If you set a value to false and provide a default, it will get autopopulated for you. In this case setting this `${{ github.token }}` means that users of your action don't need to set this value at all and it's one line easier to set up 😄
> Set a default for github_token

- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/fixtures/push_payload.json
- test/index.test.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
closes https://github.com/jonabc/licensed-ci/issues/44
Updates `utils.getBranch` to pull branch ref information from `github.context.payload` rather than `$GITHUB_REF`.  On pull request events, `GITHUB_REF` looks like `refs/pull/X/merge` which could be parsed for a pull request number.  If I did that though, I would then need to query the API to get the same pull request information that exists in github.context.payload 🤷
> Handle running licensed-ci from pull request events

- README.md
- lib/utils.js
- test/utils.test.js
closes https://github.com/jonabc/licensed-ci/issues/47
This is a small fix that reverses the order of checks when finding the branch relating to an incoming event.  It looks like PR events still have a ref property in the payload though that's not being documented anyplace I've looked 🤷 😞 
I've also used this opportunity to add a bit of extra information to the readme
cc @johlju
> Fix checks to get the branch to test from a PR

- .github/workflows/release-licenses.yml
- .github/workflows/test-licenses.yml
- README.md
closes https://github.com/jonabc/licensed-ci/issues/52
Actions still doesn't support neutral exit codes as far as I can tell, so in the meantime I've updated the code to give a better error message when using licensed-ci on a tag ref.  I've also updated the README and usage in this repo to include `tags-ignore: '**'` and give guidance against using licensed on pushed tags
> Give better error message for tags

- dist/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
closes https://github.com/jonabc/licensed-ci/issues/46
This PR attempts to address the above issue by filtering out licensed's cache paths that don't exist on disk.  The scenario mentioned in the issue is that a command entrypoint doesn't have any external dependencies, and so licensed never creates a directory on disk to hold dependency metadata.
This is a low-touch fix to check that each cache path directory exists on disk before using it as an argument to git add.
/cc @mhagger @gudmunder FYI finally getting around to addressing this, sorry for the delay
> don't include cache paths that don't exist on disk

- .github/workflows/test-licenses.yml
- .github/workflows/test.yml
update the trigger for running test actions to be on any pull request activities rather than PRs, to account for PRs opened from forks
> run tests in CI on pull request triggers

- package-lock.json
- package.json
This is a nested dependency that I think ended up as an explicit ref to force a version bump.  It's not needed any more
> remove explicit acorn reference

- dist/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
This PR updates a few issues I've seen using the action.
1. License metadata pushes aren't actually being done as the `github_token` input value 😨 .  This is due to the actions/checkout action setting `http.{server}.extraheader=AUTHORIZATION basic <token used for checkout>` in the git config by default.  That behavior can be turned off by setting `persist-credentials: false` on the action, but this action relies on that value never being set and should account for it no matter how actions/checkout is configured.
- Fixed this by using `git -c` configuration flags to override previous extraheader values for both the global `http.extraheader` and the more specific `http.{server url}.extraheader` that is set by actions/checkout.  `server url` for most cases will be `https://github.com/` but …
> Clear auth-based extra headers when pushing licensing changes and make action more reliable

- dist/index.js
- lib/utils.js
🤦  found this after some quick testing in a prod environment.  The `git config` call will return with an error exit code if there are no values set.  This is not an error case for the usage here and shouldn't be cause an error to be raised
> Don't fail git config call when no config values are set

- dist/index.js
- lib/utils.js
- test/utils.test.js
closes https://github.com/jonabc/licensed-ci/issues/96
Looks like `x-access-token` is needed in the remote url after all 😞 , I'm guessing for situations where the token isn't a PAT.  
This PR reverts that particular change from https://github.com/jonabc/licensed-ci/pull/92
cc @nadavshatz
> Reinstate x-access-token in remote url

- dist/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
This is a non-necessary fix but is a move towards the general strategy that this action should not leave lasting changes in the local git environment.  Rather than overwriting the local git config to set a user name and email this change sets the configured user name and email on individual git calls that require it with `-c user.name=... -c user.email=...`
> Set git user config per call

- dist/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
Fixes a current issue with using the action with `push` action events, the `branch` workflow strategy, and a shallow checkout from `actions/checkout`.
One of the underlying principles of this action is that it should "just work" without thrashing the local actions environment.  I tried to accomplish that by using a separate remote and only affecting branches from that remote.  I thought that would be enough to avoid interactions with shallow fetches done by default with `actions/checkout@v2`, but that was wrong. 
The error scenario comes together as a perfect storm combination of:
- the push action event, where the commit SHA is the ref head and is used by default in `actions/checkout`
- the shallow fetch here puts the commit SHA into the `.git/shallow` tracking file
- the branch …
> Use unique, unshallow branches for licensed remote

- README.md
- action.yml
- dist/index.js
- lib/utils.js
- test/utils.test.js
closes https://github.com/jonabc/licensed-ci/issues/133
This change adds in picking up the user's working branch from a few more contexts:
1. From `context.ref`, if the branch name isn't picked up from existing sources and if the ref matches the `refs/heads/*` pattern
1. From user-provided input.  If the user input is set, that value will override other potential inputs and will always be used.
cc @villelahdenvuo
> Enable schedule events by picking up branch name from more sources

- .eslintrc.json
- README.md
- action.yml
- dist/index.js
- lib/utils.js
- lib/workflows/branch.js
- lib/workflows/push.js
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
This PR updates the action to work better with PR's that Dependabot opens to update dependencies.  Licensed-ci (and github/licensed in general) has a pretty significant functional overlap with Dependabot;  when Dependabot opens PRs for dependency updates, licensed-ci will pick up the dependency version updates and update dependency metadata files.
I've found there is a non-trivial amount of friction when using licensed-ci in combination with Dependabot.  Each of the licensed-ci workflows introduce their own styles of friction, and neither of them play nice with Dependabot :/
1. push - In licensed-ci's push workflow, metadata file updates are pushed to the same branch where dependencies are updated.  When using the default commit message `Auto-update license files`, changes pushed to a …
> Enable better integration with Dependabot

- README.md
- dist/index.js
- lib/workflows/branch.js
- lib/workflows/index.js
- lib/workflows/push.js
- lib/workflows/push_for_bots.js
- test/fixtures/push_for_bots_bot_payload.json
- test/fixtures/push_for_bots_user_payload.json
- test/licensed-ci.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
- test/workflows/push_for_bots.test.js
Similar to https://github.com/jonabc/licensed-ci/pull/153, this PR aims to improve how this action works with Dependabot by specifying the action to choose a different `workflow` based on the context that the action is run in.  In this case, rather than building functionality specifically for dependabot I think it makes more sense to address this more broadly as reacting to changes made by bots vs changes made by humans.
The idea here is that humans might experience friction if a bot were to push changes directly to their working branch, in which case the `branch` workflow is more appropriate.  Bots on the other hand are more likely to be programmed to clone, fetch, or pull changes on a repo or branch every time some automation is executed.  In that scenario, pushing metadata updates …
> Add push_for_bots workflow type

- README.md
1. `actions/setup-ruby` deprecated in favor of `ruby/setup-ruby`
2. `actions/checkout` latest is now `v3`
3. `actions/setup-node` latest is now `v3`
> Update actions versions

- README.md
the NodeJS example was not using `setup-licensed`, not did it set a `runs-on` key
> Update NodeJS example

- .github/workflows/licensed-ci.yml
- .github/workflows/test-licenses.yml
- .github/workflows/test.yml
- README.md
This updates the references and usage of licensed v3 to licensed v4 in the repo.  The biggest change in the v4 release was that licensed no longer build and releases executables and requires installing licensed as a gem.  [jonabc/setup-licensed](https://github.com/jonabc/setup-licensed) has always preferred to install licensed as a ruby gem when possible, so the only updates needed to support v4 should be running the [ruby/setup-ruby](https://github.com/ruby/setup-ruby) action so that a user-modifiable ruby gems install location is available.
This PR also resolves https://github.com/jonabc/licensed-ci/issues/178.  After dropping support for the release executables, licensed is no longer tied to ruby 2.6 which was bundled into the executables.  I've set the installed ruby version to `ruby` …
> Update CI workflows and readme for running licensed v4

- README.md
This small pull request fixes an error: "_the `uses' attribute must be a path, a Docker image, or owner/repo@ref_" when copying over the full example to test the workflow.
> update workflow examples to include action ref

- dist/index.js
- lib/utils.js
- test/utils.test.js
This PR adds support for handling [`merge_group` event types from GitHub Actions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group).  The [merge_group webook payload](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group) includes a `merge_group` object with a `head_ref` field that's used here.
> Handle `merge_group` payloads

- .github/workflows/licensed-ci.yml
- .github/workflows/test-licenses.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- README.md
- package.json
- test/fixtures/testSearchResult.json
- test/utils.test.js
- test/workflows/branch.test.js
- test/workflows/push.test.js
With the transfer of this repository from `jonabc` org to `github` org, the URLs referencing the action and the statements using the action needed to be updated.  This PR updates those org references.
> replace references to jonabc org with github org

- README.md
This action is now deprecated in favor of licensee/licensed-ci.
> Update README.md with deprecation notice.
